slug: asset-categories
title: Reorganizing the Asset & Transaction Categories
client: RockWallet
role: Head of Product Design
year: 2025
category: mobile
published: true
tech_stack: [Figma, iOS, Android, CoinMarketCap, Fireblocks]
nda: false
