-- Initial schema for portfolio-federico
-- Mirrors the migration applied via Supabase MCP on project ckezhxnaampuvenyuppo.
-- Tables: projects, project_sections, project_assets, leads.
-- Storage bucket: project-assets (public read).
--
-- Note: the full-text-search tsvector is generated by an IMMUTABLE wrapper
-- function (public.projects_search_doc). Postgres refuses to treat inline
-- to_tsvector('simple', ...) as immutable inside a GENERATED ... STORED column,
-- so wrapping it in a user-defined IMMUTABLE function is the canonical fix.
-- search_path is fixed to '' and pg_catalog is schema-qualified for safety.

create or replace function public.projects_search_doc(
  title text,
  summary text,
  description text,
  tech_stack text[]
)
returns tsvector
language sql
immutable
set search_path = ''
as $$
  select
    setweight(pg_catalog.to_tsvector('pg_catalog.simple', coalesce(title, '')), 'A') ||
    setweight(pg_catalog.to_tsvector('pg_catalog.simple', coalesce(summary, '')), 'B') ||
    setweight(pg_catalog.to_tsvector('pg_catalog.simple', coalesce(description, '')), 'C') ||
    setweight(pg_catalog.to_tsvector('pg_catalog.simple', pg_catalog.array_to_string(coalesce(tech_stack, '{}'), ' ')), 'C')
$$;

create table projects (
  id uuid primary key default gen_random_uuid(),
  slug text unique not null,
  title text not null,
  role text,
  client text,
  year int,
  summary text,
  description text,
  tech_stack text[],
  metrics jsonb,
  category text check (category in ('ai','mobile','desktop','personal')),
  og_image text,
  published bool default false,
  created_at timestamptz default now(),
  search_tsv tsvector generated always as (
    public.projects_search_doc(title, summary, description, tech_stack)
  ) stored
);

create index projects_tsv_idx on projects using gin (search_tsv);
create index projects_category_idx on projects (category) where published;

create table project_sections (
  id uuid primary key default gen_random_uuid(),
  project_id uuid references projects(id) on delete cascade,
  section_type text,
  heading text,
  content_md text,
  "order" int,
  created_at timestamptz default now()
);

create table project_assets (
  id uuid primary key default gen_random_uuid(),
  project_id uuid references projects(id) on delete cascade,
  type text,
  url text not null,
  alt_text text,
  caption text,
  "order" int
);

create table leads (
  id uuid primary key default gen_random_uuid(),
  email text not null,
  name text,
  message text,
  source text default 'contact-form',
  metadata jsonb,
  created_at timestamptz default now()
);

alter table projects enable row level security;
alter table project_sections enable row level security;
alter table project_assets enable row level security;
alter table leads enable row level security;

create policy "public_read_projects" on projects
  for select using (published);

create policy "public_read_sections" on project_sections
  for select using (project_id in (select id from projects where published));

create policy "public_read_assets" on project_assets
  for select using (project_id in (select id from projects where published));

create policy "anon_insert_leads" on leads
  for insert with check (true);

-- Storage bucket for project assets (public read).
insert into storage.buckets (id, name, public)
values ('project-assets', 'project-assets', true)
on conflict (id) do nothing;

create policy "public_read_project_assets"
  on storage.objects
  for select
  using (bucket_id = 'project-assets');
